version: "0.2"
files:
  - "**/*"
ignorePaths:
  - pnpm-lock.yaml
  - .git/
  - dist/
useGitignore: true
language: en, en-GB
allowCompoundWords: true
enableGlobDot: true
words:
  - aminya
  - asan
  - ccache
  - ccmake
  - choco
  - clangd
  - clpath
  - cmake
  - cmakelint
  - cmds
  - cobertura
  - codecov
  - codeql
  - covertura
  - cpack
  - CPATH
  - Cppcheck
  - cppcoreguidelines
  - cpprc
  - cpptools
  - ctest
  - DCATCH
  - DCMAKE
  - DDEFAULT
  - dearmor
  - DFEATURE
  - DontAlign
  - eamodio
  - ehthumbs
  - Eigen
  - FLTK
  - fuzzer
  - gcov
  - gcovr
  - gedit
  - gtest
  - GTKMM
  - Hostx
  - hwrap
  - ifeq
  - IMGUI
  - inplace
  - IWYU
  - kwargs
  - lldb
  - mkdir
  - msvc
  - myproject
  - nothrow
  - nproc
  - Opencppcoverage
  - pargs
  - pnpm
  - PTRACE
  - pwsh
  - pylance
  - refreshenv
  - rmrf
  - SFML
  - socat
  - SYSREQUIRES
  - TLDR
  - TOLOWER
  - TOUPPER
  - twxs
  - vcpkg
  - vcvarsall
  - vcvarsallpath
  - VSINSTALLDIR
  - vswhere
  - webp
  - WMAIN
